title: Data Structures & Editing
nav:
  - introduction.md
  - location-of-data-files.md
  - data-file-structure-overview.md
  - platform-types.md
  - platform-characteristics.md
  - weaponsystem-types.md
  - munition-types.md
  - weapon-list-codes-new-provisional.md
  - task-force-type-filters.md
  - formation-roles.md
  - battle-planner-template-bpt-codes.md
  - mobility-types.md
  - getting-started-with-data-editing.md
  - editing-the-data.md
  - national-defaults.md
  - command.md
  - formations.md
  - units.md
  - systems.md
  - munition-types.md
  - surnames.md
  - notice.md
  - data-folder-setup.md
  - data-validation-tool.md
  - file-xls-importexport-editing.md
  - future-updates.md
