title: Scenario Design
nav:
  - Section: index.md
  - getting-started.md
  - the-top-menu.md
  - creating-a-new-scenario.md
  - battle-plans.md
  - altering-an-existing-scenario.md
  - updating-scenario-data.md
  - html-quick-reference.md
  - some-scenario-design-dos-and-donts.md
