nav:
  - 01-gameops.md
  - welcome-commander-screen.md
  - user-preferences.md
  - start-a-new-scenario.md
  - start-a-new-campaign.md
  - start-a-pbem-game.md
  - starting-a-pbem-classic-game.md
  - resuming-games.md
  - game-launch-and-user-interface.md
  - announcement-dialog.md
  - main-menu-bar.md
  - status-bar.md
  - core-game-panels.md
  - info-view-panels.md
  - staff-dialogs.md
  - the-game-map.md
  - unit-counters.md
  - specific-unit-roles.md
  - special-unit-types.md
  - order-of-battle-oob-tree.md
  - issuing-orders.md
  - plotting-movement-and-fires.md
  - standard-operating-procedures-sop.md
  - spotting-and-line-of-sight-los.md
  - combat-operations.md
  - combat-soft-factors.md
  - supply-and-logistics.md
  - time-of-day.md
  - weather.md
  - victory-conditions-and-end-game.md
  - campaign-game-play-overview.md
  - designer-notes.md

