site_name: "Flashpoint Campaigns: Cold War Guides"
site_url: https://www.ontargetsimulations.com/guides/coldwar/
validation:
  links: 
    absolute_links: relative_to_docs
watch:
  - includes
theme:
  name: material
  icon: 
    logo: material/compass-rose
  custom_dir: overrides
  palette:
    - scheme: flashpoint
  font:
    text: IBM Plex Mono
    code: Roboto Mono
  features:
    - content.code.copy
    - content.tooltips
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.expand
#    - navigation.instant
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - navigation.tracking
    - navigation.path
    # - search.suggest
    - toc.follow
#    - toc.integrate
    - navigation.instant.preview
extra_css:
  - assets/stylesheets/neoteroi-mkdocs.css
  - assets/stylesheets/extra.css
  - assets/stylesheets/mil-symbols.css
  - assets/stylesheets/force.css
plugins:
  - search:
      lang: en
      separator: '[\s\,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      prebuild_index: true
      indexing: 'sections'
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer
  - meta
#  - offline
#  - git-revision-date-localized:
#      fallback_to_build_date: true
#  - mkdocs-literate-nav
#  - mkdocs-video
#  - mermaid2
#  - live-edit
  - macros
  - autolinks
  - autorefs
 # - glightbox
  - optimize:
      optimize_png: false
  - enumerate-headings:
      toc_depth: 1
      strict: false
      include:
        - FieldManuals/*
        - Guides/*
      exclude:
        - FieldManuals/Tutorials/index.md
        - FieldManuals/game-operations/index.md
        - FieldManuals/battlefield-primer/index.md
        - FieldManuals/index.md
        - FieldManuals/hotkeys.md
      restart_increment_after:
        - FieldManuals/game-operations/welcome-commander-screen.md
        - FieldManuals/battlefield-primer/surviving-modern-warfare.md
        - FieldManuals/intermediate-tutorials/
        - FieldManuals/advanced-tutorials/
  - awesome-nav  
markdown_extensions:
  - abbr
  - tables
  - toc:
      toc_depth: 4
  - def_list
  - md_in_html
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbr.md
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.caption
  - pymdownx.blocks.tab
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - neoteroi.timeline
  - attr_list
extra:
  generator: false
  test_macro: ==yabba== ^^dabba^^ **doo**
copyright: Copyright &copy; 2025 On Target Simulations (OTS) Ltd. All Rights Reserved.