site_name: Flashpoint Campaigns Documentation
watch:
  - includes
theme:
  name: material
  palette:
    - scheme: flashpoint
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: green
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Courier Prime
    code: IBM Plex Mono
  features:
    - content.tooltips
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - search.suggest
    - toc.follow
    - toc.integrate
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/mil-symbols.css
plugins:
  - tags
  - offline
  - search
  - localsearch
  - git-revision-date-localized
#  - mkdocs-literate-nav
  - mkdocs-video
  - mermaid2
#  - live-edit
  - awesome-nav  
  - macros
  - autolinks
  - autorefs
  - enumerate-headings:
      include:
        - FCCW/FieldManuals/*.md
  - exporter:
      buttons:
        - title: Download as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes
      formats:
        pdf:
          explicit: true
          enabled: !ENV [MKDOCS_EXPORTER_PDF_ENABLED, true]
          # concurrency: 8
          stylesheets:
            - docs/assets/stylesheets/pdf.scss
          # covers:
          #  front: docs/assets/templates/covers/front.html.j2
          #  back: docs/assets/templates/covers/back.html.j2
          aggregator:
            enabled: true
            output: FCCW-FM.pdf
            covers: book
markdown_extensions:
  - meta
  - abbr
  - tables
  - toc:
      toc_depth: 3
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbr.md
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  generator: false
  test_macro: ==yabba== ^^dabba^^ **doo**