nav:
  - Section: index.md 
  - United States: United States.md
  - Belgium: Belgium.md
  - United Kingdom: United Kingdom.md
  - Canada: Canada.md
  - France: France.md
  - West Germany: West Germany.md
  - Czechoslovakia: Czechoslovakia.md
  - East Germany: East Germany.md
  - Poland: Poland.md
  - Soviet Union: Soviet Union.md