nav:
  - Section: index.md
  - combined-arms-battle.md
  - battlefield-functions-and-activities.md
  - command-and-control.md
  - spectrum-warfare.md
  - types-of-units-in-the-game.md
  - other-unit-types.md
  - weapon-types.md
  - munitions.md
  - sensors.md
  - systems.md
  - types-of-protection.md
  - nato-symbols.md
  - force-organization.md
  - counter-layout-and-map-objects.md
  - table-of-common-abbreviations.md
