nav:
  - Section: index.md
  - surviving-modern-warfare.md
  - tips-and-tricks-helpful-staff-tips.md
  - types-of-units-in-the-game.md
  - other-unit-types.md
  - weapon-types.md
  - munitions.md
  - sensors.md
  - systems.md
  - types-of-protection.md
  - nato-symbols.md
  - force-organization.md
  - counter-layout-and-map-objects.md
  - table-of-common-abbreviations.md
