nav:
  - Section: index.md
  - surviving-modern-warfare.md
  - tips-and-tricks-helpful-staff-tips.md
  - types-of-units-in-the-game.md
  - nato-symbols.md
  - force-organization.md
  - counter-layout-and-map-objects.md
  - table-of-common-abbreviations.md
  - flashpoint-campaigns-credits.md
  - ots-on-the-web.md
