nav:
  - Basic Tutorial Introduction: index.md
  - introduction.md
  - load-the-basic-operations-tutorial.md
  - user-interface-layout.md
  - standard-operating-procedure-sop.md
  - issuing-orders-to-units.md
  - command-and-control.md
  - resolving-the-battle.md
  - end-game-post-mortem.md
