nav:
  - Advanced Tutorials Introduction: index.md
  - introduction.md
  - air-assault-operations.md
  - simplified-air-assault-operations.md
  - detailed-air-assault-operation.md
  - simplified-convoy-operations.md
  - detailed-convoy-operations.md
  - transport-operations-planning.md
  - tips-for-transport-planning.md
