title: Making Mods
nav:
  - Section: index.md
  - getting-started.md
  - replacing-national-art-assets.md
  - animations.md
  - counter-art-elements.md
  - map-markers.md
  - art-restrictions.md
  - replacing-sound-assets.md
  - editing-game-ini-files.md
  - css-files.md
  - sil-making-101.md