title: Battle Planning
nav:
  - Section: index.md
  - getting-started.md
  - creating-battle-plans.md
  - battle-plans-sops.md
  - battle-plans-for-off-map-artillery-and-air-force.md
  - battle-planning-dos-and-dont.md
